name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout and Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cy:run
        env: 
          APP_URL: "http://localhost:3000/"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api.vercel.app"