name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        users: actions/setup-node@v4
        with:
          node-version: 20
          


      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api.vercel.app"
          build: npm run build
          start: npm start